CI attempt #1

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -1,7 +1,6 @@
 name: CI
 
-on:
-  pull_request
+on: pull_request
 
 permissions:
   id-token: write
@@ -21,3 +20,85 @@ jobs:
       - name: Jolt tests
         run: zig build test --summary all
 
+  build-test-server-image:
+    name: Build Zig server Docker image
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v4
+      - name: Build Docker image
+        uses: docker/build-push-action@v7
+        with:
+          context: .
+          file: ./Dockerfile
+          target: server
+          tags: ghcr.io/thepowerscompany/jolt-test-server:dev
+          cache-from: type=gha,scope=server
+          cache-to: type=gha,mode=max,scope=server
+          outputs: type=docker,dest=/tmp/jolt-test-server.tar
+      - name: Upload Docker image
+        uses: actions/upload-artifact@v4
+        with:
+          name: docker-jolt-test-server
+          path: /tmp/jolt-test-server.tar
+          if-no-files-found: error
+          retention-days: 1
+          compression-level: 9
+
+  end-to-end-tests:
+    runs-on: ubuntu-latest
+    name: E2E Tests
+    needs: build-test-server-image
+    timeout-minutes: 15
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - uses: actions/setup-node@v6
+        with:
+          node-version: 24
+          cache: "npm"
+          cache-dependency-path: ./tests/package-lock.json
+
+      - name: Install dependencies and build
+        run: npm ci
+
+      - name: Download Docker image
+        uses: actions/download-artifact@v4
+        with:
+          name: docker-jolt-test-server
+
+      - name: Run test server in background
+        run: |
+          docker load --input ./jolt-test-server.tar
+          docker run --detach --network host \
+            --name jolt_test_server \
+            ghcr.io/thepowerscompany/jolt-test-server:dev
+
+      - name: Wait for Zig server
+        run: |
+          if curl --retry 5 --max-time 5 --retry-max-time 30 --retry-all-errors --silent --fail http://localhost:3333/ping; then
+            echo "Server is running"
+          else
+            echo "Server failed to start"
+            exit 1
+          fi
+
+      - name: Run server tests
+        run: cd tests && npm run all-tests
+
+      - name: Capture Zig server logs
+        if: always()
+        run: |
+          docker logs jolt_test_server
+          docker logs jolt_test_server &> jolt_test_server.log
+          docker rm --force jolt_test_server
+
+      - uses: actions/upload-artifact@v4
+        if: failure()
+        with:
+          name: jolt_test_server.log
+          path: jolt_test_server.log
+          retention-days: 7
+          compression-level: 9
